string = 'Hello world!'.startswith('Hello') 
print(string)
string = 'Hello world!'.endswith('world!') 
print(string)
string = 'abc123'.startswith('abcdef') 
print(string)
string = 'abc123'.endswith('12') 
print(string)
string = 'Hello world!'.startswith('Hello world!') 
print(string)
string = 'Hello world!'.endswith('Hello world!')

teks = 'Hello'.rjust(10) 
print(teks)
teks ='Hello'.rjust(20) 
print(teks)
teks ='Hello World'.rjust(20) 
print(teks)
teks='Hello'.ljust(10) 
print(teks)
teks='Hello'.rjust(20, '*') 
print(teks)
teks='Hello'.ljust(20, '-') 
print(teks)
teks='Hello'.center(20) 
print(teks)
teks='Hello'.center(20, '=')
print(teks)
